---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: config-test
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: at.liwest.esb.config-test
  name: mysecret
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
type: Opaque
