kind: "Template"
apiVersion: "v1"
metadata:
  name: "ConfigTest"
  annotations:
    openshift.io/display-name: "ConfigTest"
    description: "ConfigTest instance"

parameters:
  - name: "SERVICE_NAME"
    displayName: "Service name"
    description: "The name of the related service"
    required: true

objects:
  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "${SERVICE_NAME}"
      labels:
        app: "${SERVICE_NAME}"
